version: '3.9'
services:
  web:
    image: srv-discovery:latest
    networks:
      schambeck-net:
        aliases:
          - srv-discovery
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
    ports:
      - target: 8761
        published: 8761
networks:
  schambeck-net:
    external: true
